# Generated by Django 5.2.5 on 2025-08-21 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='城市代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('response_time', models.FloatField(verbose_name='响应时间(毫秒)')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': '请求日志',
                'verbose_name_plural': '请求日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机房名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='机房代码')),
                ('address', models.TextField(blank=True, verbose_name='机房地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datacenters', to='hosts.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='主机名称')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('status', models.CharField(choices=[('active', '运行中'), ('inactive', '已停止'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='状态')),
                ('encrypted_root_password', models.TextField(verbose_name='加密的root密码')),
                ('last_password_change', models.DateTimeField(auto_now_add=True, verbose_name='密码最后修改时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='hosts.datacenter', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'ordering': ['datacenter', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hosts', models.IntegerField(default=0, verbose_name='主机总数')),
                ('active_hosts', models.IntegerField(default=0, verbose_name='运行中主机数')),
                ('inactive_hosts', models.IntegerField(default=0, verbose_name='已停止主机数')),
                ('maintenance_hosts', models.IntegerField(default=0, verbose_name='维护中主机数')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.city', verbose_name='城市')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.datacenter', verbose_name='机房')),
            ],
            options={
                'verbose_name': '主机统计',
                'verbose_name_plural': '主机统计',
                'ordering': ['-date', 'city', 'datacenter'],
                'unique_together': {('city', 'datacenter', 'date')},
            },
        ),
    ]
